version: '3'

services:
  mongo_container:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  python_app:
    build: .
    container_name: python_app
    depends_on:
      - mongo_container
    tty: true
